{
  "message":"accurate",
  "cod":"200",
  "count":1,
  "list":[
    {
      "id":2147714,
      "name":"Sydney",
      "coord":{
        "lon":151.207321,
        "lat":-33.867851
      },
      "main":{
        "temp":13.84,
        "humidity":58,
        "pressure":1029,
        "temp_min":11.67,
        "temp_max":16.67
      },
      "dt":1465979431,
      "wind":{
        "speed":1.03,
        "gust":1.54,
        "deg":0
      },
      "sys":{
        "country":"AU"
      },
      "clouds":{
        "all":0
      },
      "weather":[
        {
          "id":800,
          "main":"Clear",
          "description":"Sky is Clear",
          "icon":"01n"
        }
      ]
    }
  ]
}
